### ISSUE TITLE
Make controls for claiming/closing tasks more obvious.

### ISSUE THREAD

**Issue by eggpi** [MeghaSharma21/WorklistTool-GSoC-2018#12]
The controls for changing the status of a task in a worklist are pretty hard to find right now. We should consider something more natural like a button or dropdown in the status column of the tasks table, so that the same control is used for both viewing the current status and changing it.

**Comment by MeghaSharma21** [comment]
I was thinking of putting edit icon (like the one near the task name) along with the current status of the task. I guess a drop-down will be less intuitive than this alternative. What are your thoughts on this?

**Comment by eggpi** [comment]
Hmm, what would happen when the edit button is clicked? Would we get a pop-up like now?

I think I'd be OK with that, but it seems that, because we're just dealing with a fixed set of options, a dropdown would be the most natural element. I like that it allows the user to change the data by interacting with a single element, and it's possibly [better for accessibility](https://developer.mozilla.org/en-US/docs/Learn/Accessibility/HTML#UI_controls) by default than whatever else we come up with now.

I'm thinking something like this:

<img width="648" alt="screen shot 2018-07-30 at 09 53 21" src="https://user-images.githubusercontent.com/489134/43399539-b5a279b0-93e1-11e8-9c75-af8ac9817e95.png">

It looks kind of ugly (`<select>` is apparently not very easy to style) but should get the job done. What do you think?

**Comment by MeghaSharma21** [comment]
It has been addressed in PR [#30](https://github.com/MeghaSharma21/WorklistTool-GSoC-2018/pull/30). Please check.
