### ISSUE TITLE
Make the intended use of worklist descriptions more obvious.

### ISSUE THREAD

**Issue by eggpi** [MeghaSharma21/WorklistTool-GSoC-2018#15]
It's not totally clear what the description of a worklist is for. I can think of two easy ways to make it more useful:

- Display the description in the `show-tasks` view.
- Add a placeholder text to the input element when writing the description to suggest how it should be used. Something like "Describe what this worklist is about and what needs to be done in it"

**Comment by MeghaSharma21** [comment]
Done. Please have a look.
