### ISSUE TITLE
Autorefresh seems broken.

### ISSUE THREAD

**Issue by eggpi** [MeghaSharma21/WorklistTool-GSoC-2018#21]
Steps to reproduce:

1) Open a worklist page (e.g., https://tools.wmflabs.org/worklist-tool/show-tasks/Meghasharma213/1/)
2) Wait for it to autorefresh.

Expected result: the table with tasks gets refreshed.
Actual result: the table disappears.

**Comment by MeghaSharma21** [comment]
It works fine now. Please check.
