### ISSUE TITLE
Error when trying to create new list

### ISSUE THREAD

**Issue by ragesoss** [MeghaSharma21/WorklistTool-GSoC-2018#25]
I tried starting a new list with one article, but I got the 'Oh snap' message when I clicked submit.

Not sure whether I put in some invalid data, or if something else entirely is the problem.

![error message](https://user-images.githubusercontent.com/848483/43166614-dc432a0a-8f4b-11e8-9667-fea5011f9c8b.png)

**Comment by MeghaSharma21** [comment]
The error came because the effort estimate has to be a number between 0-100. I'm working on making the page more descriptive and intuitive as to what has to be entered in the fields. I'll intimate you once it's done.

**Comment by eggpi** [comment]
See #13 -- the idea is that we'll have a fixed set of human-readable options like "low"/"medium"/"high".
