### ISSUE TITLE
Can't create worklist from PetScan query ("PetScan articles could not be saved").

### ISSUE THREAD

**Issue by eggpi** [MeghaSharma21/WorklistTool-GSoC-2018#46]
I'm trying to create a worklist from https://petscan.wmflabs.org/?psid=5609250, but the tool just errors out:

<img width="1440" alt="screenshot 2019-02-05 at 19 12 41" src="https://user-images.githubusercontent.com/489134/52298124-29782780-297a-11e9-8078-bba25c69fd77.png">

**Comment by Jain-Aditya** [comment]
@eggpi I also tried to create the worklist with psid=560920 locally and I am facing the same issue. After looking at the debug.log, it became clear that the PetScan query is failing on being timed out. What could be the reason for the failure of this query? Also the query with psid=49883 is creating the same issue both locally as well as on toolforge.

**Comment by eggpi** [comment]
Yeah, PetScan can be quite slow sometimes. The queries are still valid, as you can see if you try to open them in your browser:

https://petscan.wmflabs.org?psid=560920
https://petscan.wmflabs.org?psid=49883

They just take a long time (sometimes almost a minute) to complete, but [in our code](https://github.com/MeghaSharma21/WorklistTool-GSoC-2018/blob/35b0bae73fc8c1d6ee161b832e5fae64e85813de/worklist/views_helper_functions/fetch_articles_from_petscan.py#L17) we're giving the request a 10s timeout. In Citation Hunt I ended up going with a 3 minute timeout for PetScan.

So there are a couple of things we can do here I think:

1. Increase the timeout for querying PetScan.
1. Improve the UX in the browser while querying PetScan:
   1. We should have some progress indicator (even if it's just an animation) for visual feedback to the user. I'm using [this spinner](http://spin.js.org/) in Citation Hunt, but it could be anything really.
   1. Display a clearer error message to the user when the query fails. For example, [this](https://github.com/eggpi/citationhunt/blob/af65785c3486829b1dacbbc688a0a8baa59912e7/chstrings/en.json#L42) is what I use in Citation Hunt.

**Comment by Jain-Aditya** [comment]
Yeah that would be better. I've tested it by increasing the timeout to 60s and it went fine. For now, Should I create a PR for increasing timeout to 3 minutes?

**Comment by eggpi** [comment]
Sure, please do! I think the UX changes are equally important though, so I suggest that we either leave this issue open after merging the timeout change, or file another one to track those. Thank you!

**Comment by Jain-Aditya** [comment]
I have opened a PR #47  for timeout change and updating the error message. Also there is already an issue #19 opened for the UI changes. So, I think we can close this issue after merging the PR #47

**Comment by Jain-Aditya** [comment]
Hi @eggpi! I think we should close this issue now, as it is resolved with the PR #47
